name: barotrauma-mod-portal
recipe: drupal9
config:
  webroot: web
  via: nginx
  # TODO: Move to local config file (should be ignored by GIT).
  xdebug: true
services:
  appserver:
    # TODO: Move to local config file (should be ignored by GIT).
    xdebug: true
    overrides:
      image: azumasv/barotraumamodportal:devwithlando-php-fpm
      environment:
        BAROTRAUMA_SOURCE_FILES: "sites/default/barotrauma"
        # Support debugging CLI with XDEBUG.
        PHP_IDE_CONFIG: "serverName=bmp"
        XDEBUG_SESSION_START: lando
