<?php

/**
 * @file
 * Global API functions and hooks.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\barotraumix\StreamWrapper\BaroStream;

/**
 * Implements hook_form_%FORM_ID%_alter().
 */
function barotraumix_form_system_file_system_settings_alter(&$form, FormStateInterface $form_state, $form_id): void {
  // Set order for existing elements.
  $form['file_public_path']['#weight'] = -10;
  $form['file_public_base_url']['#weight'] = -5;

  /** @var BaroStream $baroStreamWrapper */
  $baroStream = Drupal::service('stream_wrapper_manager')->getViaScheme('baro');
  // Define value for our own stream wrapper.
  $form['file_barotrauma_path'] = $form['file_public_path'];
  $form['file_barotrauma_path']['#title'] = $baroStream->getName();
  $form['file_barotrauma_path']['#description'] = $baroStream->getDescription();
  $form['file_barotrauma_path']['#markup'] = BaroStream::basePath();
  $form['file_barotrauma_path']['#weight'] = 0;
}
